# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shabaan.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_logan = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logan.setEnabled(True)
        self.btn_logan.setObjectName("btn_logan")
        self.horizontalLayout_3.addWidget(self.btn_logan)
        self.btn_browse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_browse.setObjectName("btn_browse")
        self.horizontalLayout_3.addWidget(self.btn_browse)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.CBox_size = QtWidgets.QComboBox(self.centralwidget)
        self.CBox_size.setObjectName("CBox_size")
        self.CBox_size.addItem("")
        self.CBox_size.addItem("")
        self.CBox_size.addItem("")
        self.horizontalLayout_3.addWidget(self.CBox_size)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sl_brightness = QtWidgets.QSlider(self.centralwidget)
        self.sl_brightness.setMouseTracking(False)
        self.sl_brightness.setMinimum(1)
        self.sl_brightness.setMaximum(20)
        self.sl_brightness.setSliderPosition(10)
        self.sl_brightness.setTracking(True)
        self.sl_brightness.setOrientation(QtCore.Qt.Vertical)
        self.sl_brightness.setObjectName("sl_brightness")
        self.horizontalLayout_5.addWidget(self.sl_brightness)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_phantom = QtWidgets.QLabel(self.centralwidget)
        self.lbl_phantom.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_phantom.sizePolicy().hasHeightForWidth())
        self.lbl_phantom.setSizePolicy(sizePolicy)
        self.lbl_phantom.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.lbl_phantom.setAutoFillBackground(False)
        self.lbl_phantom.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_phantom.setScaledContents(True)
        self.lbl_phantom.setObjectName("lbl_phantom")
        self.gridLayout.addWidget(self.lbl_phantom, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tab_15)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        
        
        
#        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab_15)
        self.graphicsView_2 = pg.PlotWidget(self.tab_15)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout_6.addWidget(self.graphicsView_2)
#        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab_15)
        self.graphicsView_3 = pg.PlotWidget(self.tab_15)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.verticalLayout_6.addWidget(self.graphicsView_3)
#        self.graphicsView = QtWidgets.QGraphicsView(self.tab_15)
        self.graphicsView = pg.PlotWidget(self.tab_15)
        self.graphicsView.setObjectName("graphicsView")
        
        
        
        
        
        self.verticalLayout_6.addWidget(self.graphicsView)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_15, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_16)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lbl_phantom_4 = QtWidgets.QLabel(self.tab_16)
        self.lbl_phantom_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_phantom_4.sizePolicy().hasHeightForWidth())
        self.lbl_phantom_4.setSizePolicy(sizePolicy)
        self.lbl_phantom_4.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.lbl_phantom_4.setAutoFillBackground(False)
        self.lbl_phantom_4.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_phantom_4.setScaledContents(True)
        self.lbl_phantom_4.setObjectName("lbl_phantom_4")
        self.gridLayout_8.addWidget(self.lbl_phantom_4, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_8.addItem(spacerItem4, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_8.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem7, 1, 0, 1, 1)
        self.horizontalLayout_12.addLayout(self.gridLayout_8)
        self.tabWidget.addTab(self.tab_16, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_5)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_logan.setText(_translate("MainWindow", "shapelogan"))
        self.btn_browse.setText(_translate("MainWindow", "browse"))
        self.comboBox.setItemText(0, _translate("MainWindow", "phantom"))
        self.comboBox.setItemText(1, _translate("MainWindow", "T1 effect"))
        self.comboBox.setItemText(2, _translate("MainWindow", "T2 effect"))
        self.comboBox.setItemText(3, _translate("MainWindow", "PD effect"))
        self.CBox_size.setItemText(0, _translate("MainWindow", "128*128"))
        self.CBox_size.setItemText(1, _translate("MainWindow", "256*256"))
        self.CBox_size.setItemText(2, _translate("MainWindow", "512*512"))
        self.lbl_phantom.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("MainWindow", "Tab 1"))
        self.lbl_phantom_4.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_16), _translate("MainWindow", "Tab 2"))

